version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./sakila-db/sakila-schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./sakila-db/sakila-data.sql:/docker-entrypoint-initdb.d/2.sql
      - ./world-db/world.sql:/docker-entrypoint-initdb.d/3.sql
#  bankapp:
#    image: mydockerapp:1.0 
#    deploy:
#      resources:
#        limits:
#          cpus: 0.50
#          memory: 256M
#        reservations:
#          cpus: 0.25
#          memory: 64M
#    environment:
#      JAVA_OPTS: -Xms64m -Xmx128m
#      SPRING_CONFIG: '/home/config/application.yaml'
#    ports:
#      - '8888:8080'
#    volumes:
#      - /home/pongpat/Documents/Fluke-Machine/downloads/recruit-prior/trainning/24052023/devconfig.yaml:/home/config/application.yaml

